FROM alpine:latest
MAINTAINER Daniel <daniel@topdevbox.com>
# How-To
# Local Build: docker build -t my/al:test .
# Local Run: docker run -i -t --name="al" my/al:test /bin/bash

RUN apk add --no-cache nano openrc
